### ISSUE TITLE
Vidproc PRs should only run kean tests if matching branch was found

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/print#43]
Otherwise, we're just running these tests on `upstream/master` again and again, wasting about 2 minutes each time.

There is currently no support for this in the config file.

**Comment by marcusnaslund** [comment]
Although, if there is a matching branch, kean tests will be run for that branch in kean, so maybe we can simply remove the kean tests from the vidproc config file. What do you think @jonathanudd ?

**Comment by jonathanudd** [comment]
Removing the kean tests from the vidproc file should be ok.
