### ISSUE TITLE
Allow manual abort for when no code is submitted

### ISSUE THREAD

**Issue by davidpiuva** [cogneco/print#59]
Useful when lots of pull requests are in queue for testing and you only change markdown files.

**Comment by fredrikbryntesson** [comment]
How should this be designed? Should print fail when we abort or should it pass? Or should we add a new state aborted?

**Comment by davidpiuva** [comment]
A new state makes sense since it neither passed nor failed then. Lower priority for a PR without a review flag would also free up time in the queue.

**Comment by marcusnaslund** [comment]
Moved to #30
