### ISSUE TITLE
Consider using helgrind to test for errors related to multithreading

### ISSUE THREAD

**Issue by ghost** [cogneco/print#81]
`valgrind -v --tools=helgrind ./program args`
can provide some useful info about possible data races and other thread-related problems in the code.

@marcusnaslund @jonathanudd @fredrikbryntesson

**Comment by marcusnaslund** [comment]
Nice. Will evaluate it later.

**Comment by ghost** [comment]
@fredrikbryntesson @marcusnaslund can we use script from https://github.com/vidhance/vidhance-sdk/pull/2069 on PRInt and close this issue ?

**Comment by fredrikbryntesson** [comment]
Good
