### ISSUE TITLE
After PRInt is (re)started, could it prioritize PRs with "final review" tag ?

### ISSUE THREAD

**Issue by ghost** [cogneco/print#84]
@marcusnaslund @fredrikbryntesson @jonathanudd ?

**Comment by marcusnaslund** [comment]
That would be nice.

**Comment by jonathanudd** [comment]
It should be possible without to much effort. The labels are fetched asynchronously now but I guess that could change and then sort all PRs based on the label.

**Comment by marcusnaslund** [comment]
With #60 you could have each PR prioritize itself if it has/gets the final review flag.

**Comment by jonathanudd** [comment]
That would also work yes :)

**Comment by ghost** [comment]
Another nice thing could be to assign lower priority to PRs with "frozen" tag.

**Comment by marcusnaslund** [comment]
> “He that can have patience can have what he will.”

**Comment by ghost** [comment]
I know you have done some work on related issue @fredrikbryntesson , what's the status of this one ? Can we close this ?

**Comment by fredrikbryntesson** [comment]
Yes it is done :)
